apiVersion: v1
kind: Service
metadata:
  name: prime-app
  labels:
    app: prime-app
spec:
  type: NodePort
  ports:
  - port: 2000
    targetPort: 2000
    nodePort: 30001
  selector:
    app: prime-app
